### ISSUE TITLE
Android.mk 没有吗

### ISSUE THREAD

**Issue by BadDeveloper2022** [Ibernato93/NativeWebSocket#1]
Android.mk 没有吗

**Comment by Ibernato93** [comment]
You can use cmake.txt instead of.mk file

**Comment by BadDeveloper2022** [comment]
@Ibernato93 Thank you for your reply. How to set the TCP DELAY option, is it the default value true?

**Comment by Ibernato93** [comment]
yes, use the default value.  If you want to change it, read the websocketpp library documentation

**Comment by BadDeveloper2022** [comment]
I cannot find any configuration related to TCP delay in its documentation.
Can you help me briefly demonstrate how to set up TCP delay in your project

**Comment by BadDeveloper2022** [comment]
@Ibernato93

**Comment by Ibernato93** [comment]
Sorry but I don't have much time available. Also check the boost documentation.

What is your purpose?

**Comment by BadDeveloper2022** [comment]
Currently, using this class library to interact with websockets has a significant latency. I want to set this value.
@Ibernato93 
I need a delay within 100MS, and in some network situations, the delay is quite high.
I directly modified the default values in the source code, but I couldn't find them

**Comment by Ibernato93** [comment]
you need to set tcp::no_delay.

Are you sure you are implementing correctly in Android? I used this project for sending frames and had no problems.

Also, I think you have to handle slow connection situations

**Comment by BadDeveloper2022** [comment]
@Ibernato93 
There's no way. Currently, in other network situations, there is no problem.
In the case of 5G networks, the latency is a bit high. At present, the download speed of 5G is fast, but the stability is not very good.
I want to set this value to see if it has any effect.
Does this value default to false
